In [2]:
import numpy as np
from scipy import stats

In [15]:
np.random.seed(0)

In [19]:
data = np.random.randint(0,100, 10000)
mean = np.mean(data); print('평균값', mean.round(2))
median = np.median(data); print('중앙값', median)
print('최빈값', stats.mode(data).mode[0])

평균값 49.82
중앙값 50.0
최빈값 90


In [7]:
mode = stats.mode(data)

In [9]:
print(dir(mode))

['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmul__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '_asdict', '_field_defaults', '_fields', '_fields_defaults', '_make', '_replace', 'count', 'index', 'mode']


In [11]:
stats.mode(data).mode

array([74])

In [20]:
points = np.random.randint(0, 100, 20)

In [21]:
points

array([99, 57, 50,  3, 45, 27, 62,  4,  5, 41, 10, 63, 92, 55, 12, 49, 49,
       99, 35, 96])

In [22]:
from scipy import stats

In [34]:
x_bar, mu, sigma, n = 297, 300, 15, 100

t_sample = (x_bar- mu)/(sigma/np.sqrt(float(n)))
print('검정통계량:', np.round(t_sample,2))

검정통계량: -2.0


In [35]:
t_sample

-2.0

In [36]:
alpha = 0.05
t_alpha = stats.t.ppf(alpha, n-1)
print('t-table로부터의 임계값:' , np.round(t_alpha,3))

t-table로부터의 임계값: -1.66


In [37]:
p_val = stats.t.sf(np.abs(t_sample), n-1)

In [38]:
p_val
print(('t-table의 아래쪽 꼬리 p값:', np.round(p_val,4)))

('t-table의 아래쪽 꼬리 p값:', 0.0241)


In [39]:
#카이검정에 관련한 예제풀이
import numpy as np
import pandas as pd
from scipy import stats

In [42]:
np.random.seed(0)
smoke = ['안함', '가끔', '매일', '심함']
exercise = ['안함', '가끔', '매일']
data = {
    'smoke' : np.random.choice(smoke, size=500),
    'exercise' : np.random.choice(exercise, size=500)
}

In [45]:
df = pd.DataFrame(data)

In [46]:
df

smoke exercise
0      안함       안함
1      심함       안함
2      가끔       매일
3      안함       가끔
4      심함       가끔
..    ...      ...
495    매일       안함
496    심함       안함
497    매일       가끔
498    가끔       안함
499    매일       매일

[500 rows x 2 columns]

In [47]:
xtab = pd.crosstab(df.smoke, df.exercise)

In [48]:
xtab

exercise  가끔  매일  안함
smoke               
가끔        38  39  45
매일        34  44  33
심함        45  44  51
안함        47  41  39

In [51]:
contg = stats.chi2_contingency(observed=xtab)

In [52]:
contg

(4.064739553068125,
 0.667915629272182,
 6,
 array([[40.016, 40.992, 40.992],
        [36.408, 37.296, 37.296],
        [45.92 , 47.04 , 47.04 ],
        [41.656, 42.672, 42.672]]))

In [53]:
p_val = np.round(contg[1],3)

In [54]:
p_val

0.668